import os
import re
import json
import joblib
import pandas as pd
import numpy as np
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List, Optional
from sklearn.metrics.pairwise import cosine_similarity

app = FastAPI(title="Ultra-Lightweight Pet Vet AI Gateway", version="4.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)

_HERE = os.path.dirname(os.path.abspath(__file__))
ASSETS_DIR = os.path.join(_HERE, "assets")

# Load all assets at startup
model       = joblib.load(os.path.join(ASSETS_DIR, "model.joblib"))
vectorizer  = joblib.load(os.path.join(ASSETS_DIR, "tfidf_vectorizer.joblib"))
tfidf_matrix = joblib.load(os.path.join(ASSETS_DIR, "tfidf_matrix.joblib"))

with open(os.path.join(ASSETS_DIR, "encoders.json"))    as f: encoders     = json.load(f)
with open(os.path.join(ASSETS_DIR, "disease_info.json")) as f: disease_info = json.load(f)
with open(os.path.join(ASSETS_DIR, "text_labels.json"))  as f: text_labels  = json.load(f)

master_symptoms = encoders["symptoms"]

# Load synonym rules from encoders.json (generated by local_pretrain.py).
# This keeps the API and the pre-trainer perfectly in sync.
SYNONYM_RULES: dict = encoders.get("synonym_rules", {})


# ── Pydantic Models ──────────────────────────────────────────────────────────

class TextRequest(BaseModel):
    text: str

class PredictRequest(BaseModel):
    animal_type: str
    symptoms: List[str]
    temperature: Optional[float] = None
    heart_rate: Optional[float] = None

class PredictResult(BaseModel):
    disease: str
    confidence: float
    urgency: str
    description: str
    treatment: str
    prevention: str


# ── Helpers ──────────────────────────────────────────────────────────────────

def get_urgency(disease_name: str) -> str:
    name_lower = disease_name.lower()
    if any(c in name_lower for c in ["parvovirus", "rabies", "bloat", "anthrax", "foot and mouth", "african swine"]):
        return "Emergency"
    if any(m in name_lower for m in ["healthy", "pregnancy"]):
        return "Monitor"
    return "Schedule Vet Visit"


# ── Routes ───────────────────────────────────────────────────────────────────

@app.get("/")
def health_check():
    return {"status": "ok", "version": "4.0.0", "symptoms": len(master_symptoms)}


async def _extract_symptoms_logic(req: TextRequest):
    """Core logic shared by both extract-symptoms route aliases."""
    if not req.text.strip():
        return {"matched_symptoms": []}
    
    user_query = req.text.lower()
    detected = []

    # ── Layer 1: Direct substring check ─────────────────────────────────────
    for sym in master_symptoms:
        if sym.lower() in user_query and sym not in detected:
            detected.append(sym)
            
    # ── Layer 2: Rule-based synonym regex matching ───────────────────────────
    for sym, keywords in SYNONYM_RULES.items():
        if sym in master_symptoms and sym not in detected:
            for kw in keywords:
                if re.search(r'\b' + re.escape(kw) + r'\b', user_query):
                    detected.append(sym)
                    break

    # ── Layer 3: TF-IDF cosine similarity fallback ───────────────────────────
    query_vector = vectorizer.transform([user_query])
    similarities = cosine_similarity(query_vector, tfidf_matrix)[0]
    
    top_indices = np.argsort(similarities)[::-1][:8]
    for idx in top_indices:
        if similarities[idx] > 0.25:
            label_entry = text_labels[idx]
            # Handle both list and string labels (list is new format, string is legacy)
            if isinstance(label_entry, list):
                for sym in label_entry:
                    if sym in master_symptoms and sym not in detected:
                        detected.append(sym)
            elif isinstance(label_entry, str):
                if label_entry in master_symptoms and label_entry not in detected:
                    detected.append(label_entry)
                    
    return {"matched_symptoms": detected}


@app.post("/extract-symptoms")
async def extract_symptoms_hyphen(req: TextRequest):
    """Translates free text to matching symptom checkboxes (hyphen path)."""
    return await _extract_symptoms_logic(req)


@app.post("/extract_symptoms")
async def extract_symptoms_underscore(req: TextRequest):
    """Translates free text to matching symptom checkboxes (underscore alias)."""
    return await _extract_symptoms_logic(req)


@app.post("/predict", response_model=List[PredictResult])
def predict(req: PredictRequest):
    try:
        species_list = encoders["species"]
        if req.animal_type not in species_list:
            raise HTTPException(
                status_code=400,
                detail=f"Species '{req.animal_type}' is not supported. Supported: {species_list}"
            )
        sp_enc = species_list.index(req.animal_type)

        species_vitals = encoders.get("healthy_vitals", {}).get(req.animal_type, {"temp": 38.5, "hr": 85.0})
        temp = req.temperature if req.temperature is not None else species_vitals["temp"]
        hr   = req.heart_rate  if req.heart_rate  is not None else species_vitals["hr"]

        sym_list = encoders["symptoms"]
        sym_vec  = [1 if s in req.symptoms else 0 for s in sym_list]

        features = pd.DataFrame(
            [[sp_enc, temp, hr] + sym_vec],
            columns=encoders["feature_names"],
        )

        probs = model.predict_proba(features)[0]

        # Prevent false-positive pregnancy predictions when no pregnancy indicators are present
        pregnancy_indicators = {
            "Nesting Behavior",
            "Clear Vaginal Discharge",
            "Bloody Vaginal Discharge",
            "Purulent Vaginal Discharge",
            "Fetal Heart Sound Detected",
            "Increased Appetite",
        }
        has_pregnancy_indicator = any(s in req.symptoms for s in pregnancy_indicators)
        if not has_pregnancy_indicator:
            try:
                preg_idx = encoders["disease"].index("Pregnancy")
                probs[preg_idx] = 0.0
                if probs.sum() > 0:
                    probs = probs / probs.sum()
            except ValueError:
                pass

        top3 = np.argsort(probs)[::-1][:3]

        results = []
        for idx in top3:
            conf = round(float(probs[idx]) * 100, 1)
            if conf < 5.0: continue
            name = encoders["disease"][idx]
            info = disease_info.get(name, {})
            results.append(
                PredictResult(
                    disease=name,
                    confidence=conf,
                    urgency=get_urgency(name),
                    description=info.get("description", "No details available."),
                    treatment=info.get("treatment", "Consult a vet."),
                    prevention=info.get("prevention", "Maintain general hygiene care."),
                )
            )
        return results
    except HTTPException as he:
        raise he
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))